CC = g++
CCFLAGS =
LIBS = -lglut -lGLU -lGL
TARGETS = project3.cpp, volumeObjects.cpp

.PHONY: all
all:
	$(info $(TARGETS))

# Targets
project3:
	$(CC) $(CCFLAGS) project3.cpp $(LIBS) -o project3
	./project3

volumeObjects:
	$(CC) $(CCFLAGS) volumeObjects.cpp $(LIBS) -o volumeObjects
